Create landing page for mobile portfolio
eamador1/portfolio pull request #1
Opened 2023-04-26 21:59 UTC by eamador1

In this project, the following was done:

- [ ] Create a landing page for mobile devices using HTML5 and CSS .
- [ ] Install and run linters

2023-04-26 22:18 UTC, Shisui6 requested changes
Hi @eamador1, 

# Requires Changes 🍀
You have done a great job so far!👏👏
Your design is good 🖼️, and your code follows best practices. However, there are a few issues that you still need to work on🪲.

## Highlights
- Headline section created ✅
- Nice design ✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 22:18 UTC, Shisui6 commented on index.html
> +        </div>
Kindly wrap your headline section in a `<section>` tag🙏. This is for semantic reasons as the section tag is used to represent a generic standalone section of the document

2023-04-26 22:18 UTC, Shisui6 commented on index.html
> +              </div>
Kindly update this element to use a `<ul>` tag instead of a `<div>` tag. This is for semantic reasons as ul tags are used to wrap most lists in a webpage

- In addition to that, please wrap each img in a `<li>` tag and make sure that the images are all links using an `<a>` tag. Your final code should look similar to something like this
`<ul>`
     `<li><a><img/></a></li>`
     `<li><a><img/></a></li>`
     `<li><a><img/></a></li>`
`</ul>`

2023-04-26 22:18 UTC, Shisui6 commented on style.css
> +
Kindly remove the default margin and padding applied to the body element to make your design match the figma design🙏

Your design:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/37116322/234714999-83b98359-783e-4081-82c5-2ad16e777e0e.png">

2023-04-26 22:30 UTC, eamador1 commented on style.css
> +
@Shisui6 Hi! Thank you for your review. 😃 I am not understanding what margin and padding you are referring to. I thought I had done a decent job doing that. I would appreciate an example of what is wrong.

2023-04-26 22:50 UTC, eamador1 commented on style.css
> +
@Shisui6 Nevermind! I got it! Thank you.

2023-04-27 03:04 UTC, eamador1 commented on style.css
> +
@Shisui6 Hi again. Actually I did not get it 😃 I was trying to get rid of the margin you mentioned by writing the code in CSS :   body { margin: 0;} but it did not work.

I inspected the body but it is an user agent style sheet (as you can see in the image below) which apparently means that it is set up by google chrome, and it has to be changed in google chrome, which goes beyond the scope of this project and makes no sense for me to do it. Please, if I am wrong and you or a future code reviewer can help me, it will be greatly appreciated. Thankyou (cheers)

<img width="321" alt="Screen Shot 2023-04-26 at 20 54 01" src="https://user-images.githubusercontent.com/124623610/234748326-e7e51a74-0422-4d4a-b107-f87a194b188e.png">

2023-04-27 03:46 UTC, eamador1 commented
Since the last review, the following changes were made:

- [ ] Add section tag to wrap landing page code
- [ ] Add ul tag and li tag to links

2023-04-27 04:14 UTC, roshan-bajgain requested changes
Hi @eamador1, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Good job on request changes ✔️ 
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 04:14 UTC, roshan-bajgain commented on index.html
> +        </ul>
- [ ] As I notice that previously the design was fine so the previous reviewer did not give changes to it but I notice some designs is changed now please implement it to match the Figma design
- [ ] If you see the Figma design then the background color used there is different please use it. `background: #3C3A39;`
- [ ] If you see the social media links there is `.` on each icon to remove it using `list-style: none;` to `li` items 
- [ ] [Optional] Please make more gap to the social media icons so it matches the design.
### Your design 
![his](https://user-images.githubusercontent.com/81727988/234756998-02b962d1-686a-4862-907c-b63807e5dea3.png)

### Figma design
![fimga](https://user-images.githubusercontent.com/81727988/234757014-49c71a1b-52d2-4bfa-b0e8-835d13b872b9.png)

2023-04-27 08:55 UTC, Shisui6 commented on style.css
> +
Hey @eamador1, apologies for the late reply. To fix the problems mentioned above, you can apply the following styles
- Add `* {
  box-sizing: border-box;
}` at the top of the CSS file

- Remove `display: block` from the body
- Remove `height: 0` from `.container-header`
- Add `margin-top: 0` to `.button-list`

Hope this helps👍

2023-04-27 16:08 UTC, eamador1 commented on style.css
> +
👏🏼👏🏼👏🏼 Thank you. You are great!

2023-04-27 16:26 UTC, eamador1 commented
Since the last review, the following changes were made:

- [ ] Change navigation var background color
- [ ] Change navigation icons to list-style: none
- [ ] Give more gap between icons

2023-04-27 18:04 UTC, usorfaitheloho requested changes
Hi @eamador1 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Implemented most of the changes suggested by the previous reviewer 👍 
- Good PR
- Good commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ]  Please i'd suggest you reduce the spacing here to give a viewer a good UI experience when your portfolio is visited.

this is what you have
![top](https://user-images.githubusercontent.com/20537712/234952374-efdd69b6-b372-40ca-86aa-be3c1b425f83.PNG)

Figma design

![figma](https://user-images.githubusercontent.com/20537712/234952832-494e05ef-096c-41ce-9ec3-0c85670dab2d.PNG)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I str
ongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 18:04 UTC, usorfaitheloho commented on style.css
> +}
Hello @eamador1 ,
Good job implementing the previous changes suggested by the last reviewer 👍 , Unfortunately, your design still looks quite different from the figma design. The previous reviewer suggested you remove the `.` in the lists by adding `list-style:none` and this worked well but gave you a really wide spacing in your social icons and this is because you used a very wide width of `35vh` , please I'd suggest you reduce to around `20vh` and you'd have a perfect replica of the design 😄  

your design :

![footer-wrong](https://user-images.githubusercontent.com/20537712/234950996-615553da-279f-4b4b-912b-f9fa8242323c.PNG)

The figma design 👍

 
![footer-right](https://user-images.githubusercontent.com/20537712/234951107-509689c7-3819-4c5f-ac32-7f46c85edbcd.PNG)

2023-04-27 18:35 UTC, eamador1 commented
Since the last review, the following was done:

- [ ] Decrease the padding between the navigation bar and text
- [ ] Decrease the container-logos width

2023-04-27 18:40 UTC, eamador1 commented
Since the last review, the following changes were:

- [ ] Decrease container-logos width
- [ ] Lower padding between navigation bar and text

2023-04-27 18:49 UTC, eamador1 commented
Since last review, the following changes were made:

- [ ] Decrease padding between navigation bar and text
- [ ] Decrease width  container-logos

2023-04-27 19:07 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @eamador1 

Your project is complete! Great job for implementing the changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- figma design followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 19:07 UTC, tufoinnkuo10 commented on index.html
> +        <header class="container-header">
- [optional] the toolbar section should be inside a header tag and the headline section inside a section tag. your header tag is inside the section tag. kindly fix that for semantic reasons.
- also you can remove the logo from the nav tag and keep just the hamburger icon inside.

2023-04-27 19:07 UTC, tufoinnkuo10 commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
- [optional] to keep your README more clean, i advise you remove the live demo section for now since your work is yet to be deployed.. You can add this later on when you have a deployment link.

2023-04-27 19:54 UTC, merged