Create works section for mobile portfolio project
eamador1/portfolio pull request #2
Opened 2023-04-28 20:52 UTC by eamador1

The following additions were made to the portfolio project:

- [ ] Create works branch
- [ ] Add works section to portfolio project
- [ ] Check linters working properly

2023-04-29 18:54 UTC, Abenezer-Tilahun requested changes
Hi @eamador1    , 

Great job for implemented  the some of the Project Requirement , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No linters error
✔️ You used correct Git Hub-Flow.
✔️ Professional README 
✔️ Good Commit Messages 


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 18:54 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] As stated in the project requirement Kindly Make sure the content of the "About myself" section is aligned with `flexbox` instead of the use CSS` Grid`.
![Capture](https://user-images.githubusercontent.com/93598189/235319302-a2142cf3-cb24-478a-b531-b6ce661155be.PNG)

2023-04-29 18:54 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] As stated in the project requirement Kindly I recommend you to Implement the button interactions (enable, hover, etc.) Just Like the Figma Design.
![Capture](https://user-images.githubusercontent.com/93598189/235319434-ca769b87-b6b3-49e2-aa81-01c293ba7b3d.PNG)

2023-04-29 21:05 UTC, eamador1 commented
Since the last review, the following changes were made:

- [ ] Align both sections with flexbox
- [ ] Add hover and pressed effect on buttons

2023-04-29 21:49 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @eamador1   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
 :heavy_check_mark: Linters are passing.
:heavy_check_mark: You have a good code structure.
:heavy_check_mark: Linters are green
 
 ## Required Change
- [ ] Check under the review

 ## Optional suggestions 
- [ ] Check under the review

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 21:49 UTC, Alfredbis29 commented on style.css
> +.container-aboutme {
- [ ]  As mentioned by the previous reviewer, it is a project requirement to align all contents of the "About me" section `.container-aboutme` with flexbox. Kindly update the main container of this section to meet this requirement. 

<img width="575" alt="image" src="https://user-images.githubusercontent.com/88894525/235325286-8af650d9-3161-47ee-9dd3-a50076956046.png">

2023-04-29 21:49 UTC, Alfredbis29 commented on style.css
> +  width: 61px;
[OPTIONAL] Although optional, it is considered good practice to use responsive values in your CSS rules, such as percentages (e.g. `width: 80%`) instead of pixels. This will make your design more adaptable to different screen sizes and improve the overall user experience. Thank you for considering this suggestion.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/88894525/235325497-b3c478b1-7c22-46d9-87eb-ddfad62c00ba.png">

2023-04-29 22:55 UTC, eamador1 commented
Since the last review, the following changes were applied:

- [ ] Add flexbox to .container-aboutme
- [ ] Use responsive values in CSS rules where had not been applied [optional]

2023-04-29 23:01 UTC, Trast00 approved these changes
# Approved 🟢
Hi @eamador1 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![allfather-approves-approved](https://user-images.githubusercontent.com/74411135/225065704-3948f35e-94b9-4440-a31a-29bba50b3c4d.gif)

## Highlights
- Project look awsome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 23:11 UTC, merged

2023-05-02 14:26 UTC, eamador1 commented on style.css
> +  height: 6vh;
I kindly suggest could use em, rem or percentage instead pixels. For the buttons width, please use vw unit. This is done so that the size of the element changes as the screen grows or shrinks.