Create portfolio desktop version
eamador1/portfolio pull request #4
Opened 2023-05-04 16:49 UTC by eamador1

Since the last review, the following changes were made to the project:

- [ ] Create desktop version
- [ ] Check linters are working properly

2023-05-04 18:44 UTC, divinecharlotte requested changes
Hi @eamador1     , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- Descriptive Pr 👍
- linters are passing 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 18:44 UTC, divinecharlotte commented on index.html
> +        <li class="navlink envelope"><img src="img/envelope.png" class="Envelope-Image"></li>
- [ ] kindly consider making sure that on any screen bigger than 768px in width the logo is still being displayed to implement exactly the given design check the image below how your design is different from the provided one
- your design 👇 
<img width="832" alt="Screen Shot 2023-05-04 at 20 10 33" src="https://user-images.githubusercontent.com/60146030/236292227-5761ff12-daaa-4568-84eb-18b34280bdfd.png">


- Figma design 👇 
<img width="713" alt="Screen Shot 2023-05-04 at 20 11 36" src="https://user-images.githubusercontent.com/60146030/236292362-ad248686-f703-41ac-994c-ef44eaf9046d.png">

2023-05-04 18:44 UTC, divinecharlotte commented on style.css
> +  }
- [ ] kindly consider removing the white margin on this section to make it look exactly as the one given check the difference below 
- your design 👇 
<img width="771" alt="Screen Shot 2023-05-04 at 20 14 05" src="https://user-images.githubusercontent.com/60146030/236293708-73f33450-d0bf-4e36-9170-aeba4acbc3e3.png">

- Figma design 👇 
<img width="714" alt="Screen Shot 2023-05-04 at 20 19 57" src="https://user-images.githubusercontent.com/60146030/236293960-24dbc145-5348-4ae1-acaa-6267a327294c.png">

2023-05-04 18:44 UTC, divinecharlotte commented on index.html
> +</div>
- [ ] kindly consider making sure that this section on your desktop version looks like the one given in the design you may do so by aligning the grey line in the place it's aligned on Figma doing   that will help you to implement exactly what was expected to be delivered check the images below to understand this clearly
- your design 👇 
<img width="1277" alt="Screen Shot 2023-05-04 at 20 30 02" src="https://user-images.githubusercontent.com/60146030/236296512-33d6e5b6-06ef-42ef-a410-bec08fedb784.png">

- Figma design 👇 
<img width="800" alt="Screen Shot 2023-05-04 at 20 31 03" src="https://user-images.githubusercontent.com/60146030/236296686-ffa53e87-a766-47e6-8bf2-372d80732e81.png">

2023-05-04 18:44 UTC, divinecharlotte commented on index.html
> +  </div>
- [ ] kindly consider making sure that when the project is hovered on with the mouse the description and dark opacity disappears and a `See Project` button appears to the bottom of the image and takes the whole image width mentioned to meet the below requirement **refer on the first card on Figma design on how this will be implemented**
> Lastly, when the project is hovered on with the mouse the description and dark opacity disappears and a `See Project` button appears to the bottom of the image and takes the whole image width mentioned button should take you to the Live Demo of the project or to the GitHub repository.

consider doing so on every single project you

2023-05-04 18:44 UTC, divinecharlotte commented on index.html
>    <hr class="division division-line2"></hr>
- [ ] kindly consider decreasing the padding of this line and give it some margin to make it look exactly as the one given in the design
- your design 👇 
<img width="1282" alt="Screen Shot 2023-05-04 at 20 39 11" src="https://user-images.githubusercontent.com/60146030/236298620-2a61ab9b-6099-4b33-8d6e-39fb341b1e75.png">

- Figma design 👇 
<img width="800" alt="Screen Shot 2023-05-04 at 20 39 42" src="https://user-images.githubusercontent.com/60146030/236298750-44197470-9ccb-4f45-ae97-a0c5654cf4ca.png">

2023-05-04 18:57 UTC, eamador1 commented on style.css
> +  }
@divinecharlotte 😀

🫡 I would gladly do that but I have not been able to do it. I understand that the browser puts that margin by default. I put the code below, recommended by another code reviewer but it did  work. My margins in the containers are zero. 🙏🏼


<img width="282" alt="Screen Shot 2023-05-04 at 12 49 04" src="https://user-images.githubusercontent.com/124623610/236301249-4d5ebd9d-ad82-4009-ba40-c3a0a4907a7d.png">

2023-05-05 22:41 UTC, eamador1 commented
Since the last code review, the following changes were made:

- [ ] Make header responsive
- [ ] Add hover effect to cards
- [ ] Change work-section header 
- [ ] Style division lines according to  figma

2023-05-06 00:18 UTC, taldr27 requested changes
# Status: Required Changes ♻️♻️

Hi @eamador1, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![almost](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Incorporates feedback from previous code reviews.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

------
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in @taldr27 your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-06 00:18 UTC, taldr27 commented on index.html
>        <li class="item item-ruby">Ruby</li>
- [ ] I noticed that you incorporated the feedback from the previous reviewer, but I wanted to point out that **it may not have been implemented correctly**. The `See project` button appears to be located below the card, which is causing your other projects to be pushed down. However, if you reference the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=34-1278&t=TtUuz1aY8ZMPpXtJ-0), you'll notice that the button should be placed inside the card. 🙋‍♂️

  ### Your design:
  ![image](https://user-images.githubusercontent.com/107952724/236586644-a5672ab2-c748-4c85-97f4-e07867905aa6.png)
  
  ### Figma design:
  ![image](https://user-images.githubusercontent.com/107952724/236586272-f9a85f92-22d1-422c-9e27-13c1a1a9ebe6.png)

2023-05-06 00:18 UTC, taldr27 commented on index.html
>    </div>
- [ ] **[OPTIONAL]** You did an excellent job on your `About me` section! I have a small suggestion to make it even more consistent with the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=34-1278&t=TtUuz1aY8ZMPpXtJ-0). You can apply this recommendation to your form button as well. 😉

  ### Your button:
  ![image](https://user-images.githubusercontent.com/107952724/236587116-f3583679-2bc0-4bc4-b355-e3ccd9a320b2.png)
  
  ### Figma design:
  ![image](https://user-images.githubusercontent.com/107952724/236587417-01b4fdb8-bbc1-4bdd-9724-c965f7e4d894.png)

2023-05-06 17:33 UTC, eamador1 commented
Since the last code review, the following changes were made:

- [ ] Adjust the card hover size 
- [ ] Adjust the button width of the About me section [optional]

2023-05-06 18:00 UTC, LionRouge1 requested changes
Hi @eamador1, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-06 18:00 UTC, LionRouge1 commented on index.html
>        <li class="item item-ruby">Ruby</li>
- [ ] Nice work making the changes :clap:  However the new changes that you made distort your cards, Kindly make sure you stick to the Figma design as much as possible
### Your design :point_down: 
![Screenshot from 2023-05-06 17-54-16](https://user-images.githubusercontent.com/91142432/236639653-384afdb3-28bf-4d81-80a4-1a6ba7ee8b9e.png)
### What it is supposed to look like :point_down: 
![](https://user-images.githubusercontent.com/107952724/236586272-f9a85f92-22d1-422c-9e27-13c1a1a9ebe6.png)

2023-05-06 21:48 UTC, eamador1 commented
Since the last code review, the following changes were made:

- [ ] Adjust the background image in cards in the desktop version

2023-05-06 21:57 UTC, mckent05 approved these changes
Hi @eamador1, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Your desktop version is ready, well done 👍 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 07:32 UTC, ahmetbozaci commented
### Hello @eamador1 
### _This is an additional review as a result of the second opinion request._ 


- It looks like your project is approved. 

If you have any questions, please don't hesitate to contact me. 

___



### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-05-08 15:44 UTC, merged